from fpdf import FPDF
from datetime import datetime
import os

class PolypReport(FPDF):
    def header(self):
        # Logo placeholder (can be added later)
        self.set_font('helvetica', 'B', 20)
        self.set_text_color(0, 100, 150)
        self.cell(0, 10, 'PolypVision AI - Clinical Report', ln=True, align='C')
        self.ln(5)
        self.set_draw_color(0, 100, 150)
        self.line(10, 25, 200, 25)
        self.ln(10)

    def footer(self):
        self.set_y(-15)
        self.set_font('helvetica', 'I', 8)
        self.set_text_color(128, 128, 128)
        self.cell(0, 10, f'Page {self.page_no()} | Generated by PolypVision AI System', align='C')

def generate_medical_report(output_path, detections, processing_time):
    pdf = PolypReport()
    pdf.add_page()
    
    # Metadata
    pdf.set_font('helvetica', 'B', 12)
    pdf.set_text_color(0, 0, 0)
    pdf.cell(0, 10, f"Date: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}", ln=True)
    pdf.cell(0, 10, f"Analysis Duration: {processing_time}", ln=True)
    pdf.ln(5)

    # Summary Stats
    polyp_count = len(detections)
    pdf.set_font('helvetica', 'B', 14)
    pdf.set_fill_color(240, 240, 240)
    pdf.cell(0, 10, f"Detection Summary: {polyp_count} Polyp(s) Found", ln=True, fill=True)
    pdf.ln(5)

    # Detailed Table
    if polyp_count > 0:
        pdf.set_font('helvetica', 'B', 10)
        pdf.cell(30, 10, "ID", 1)
        pdf.cell(80, 10, "Bounding Box (x1, y1, x2, y2)", 1)
        pdf.cell(40, 10, "Confidence Score", 1)
        pdf.ln()

        pdf.set_font('helvetica', '', 10)
        for i, det in enumerate(detections):
            pdf.cell(30, 10, f"Polyp #{i+1}", 1)
            pdf.cell(80, 10, f"({det['x1']}, {det['y1']}, {det['x2']}, {det['y2']})", 1)
            pdf.cell(40, 10, f"{det['score']:.4f}", 1)
            pdf.ln()
    else:
        pdf.set_font('helvetica', 'I', 12)
        pdf.cell(0, 10, "No abnormalities detected in the provided sample.", ln=True)

    pdf.ln(20)
    pdf.set_font('helvetica', 'B', 10)
    pdf.multi_cell(0, 10, "Disclaimer: This report is generated by an AI system and is intended for clinical assistance only. Final diagnosis must be performed by a qualified medical professional.")

    pdf.output(output_path)
    return output_path
